Refactored server auth.
OpenSlides/openslides-manage-service pull request #121
Opened 2021-12-07 00:21 UTC by normanjaeckel

2021-12-07 10:24 UTC, ostcar requested changes
Some remarks. Most of them are suggestions. Only the removal ob `bytes.Equal` is important.

I have not tested this. Please test at least once, that it is not possible to access the tunnel and one non-streaming command without the password or a wrong password.

2021-12-07 10:24 UTC, ostcar commented on pkg/server/server.go
> +	sec, err := shared.ServerAuthSecret(s.config.PasswordFile, s.config.OpenSlidesDevelopment)
Please cache the secret in the in `srv` object. You can do this in the `newServer` function or with [sync.Once](https://pkg.go.dev/sync#Once.Do) inside this function.

2021-12-07 10:24 UTC, ostcar commented on pkg/server/server.go
> +func serverAuth(ctx context.Context, s *srv) error {
This function looks like it could be a method on `*srv`

```go
func (s *srv) serverAuth(ctx context.Context) error
```

2021-12-07 10:24 UTC, ostcar commented on pkg/shared/shared.go
> +	if !dev {
In go, you should try not to indent the happy path: https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88

I would do it like this:

```go
func ServerAuthSecret(secretFile string, devEnv string) ([]byte, error) {
  if dev, _ := strconv.ParseBool(devEnv); dev {
    return []byte(DevelopmentPassword), nil
  }

  pw, err := os.ReadFile(...)
  ...
  return pw, nil
}
```

2021-12-07 10:24 UTC, ostcar commented on pkg/shared/shared.go
> +func ServerAuthSecret(secretFile string, devEnv string) ([]byte, error) {
Are you sure this function has to be public? If not, you should rename it to `serverAuthSecret`.

2021-12-07 10:24 UTC, ostcar commented on pkg/server/server.go
> +func serverAuthUnaryInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
Maybe rename this function to `authUnaryInterceptor`. The package is called `server`. So there is no need to call the function `serverFOO`. See https://go.dev/blog/package-names#naming-package-contents

This rule is not so important on unpublished functions but I think it a a good style to use it also on unpublished function names.

There are more examples here in this file.

2021-12-07 10:24 UTC, ostcar commented on pkg/shared/shared.go
> +	pw := []byte(DevelopmentPassword)
Are you sure the constant `DevelopmentPassword` has to be public? Maybe rename it to `developmentPassword`

2021-12-08 20:59 UTC, normanjaeckel commented
The password protection works but the error message in the tunnel case is not good. I make an extra issue for that.

2021-12-08 20:59 UTC, merged